server {
    listen 80;
    listen [::]:80;
    server_name app-test.supercoop.fr;

    access_log /data/supercoop/app-pwa-recette/logs/nginx.access.log;
    error_log /data/supercoop/app-pwa-recette/logs/nginx.error.log;

    root /data/supercoop/app-pwa-recette;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
